apiVersion: v1
kind: Pod
metadata:
  name: identity-pod
  labels:
    name: web
spec:
  containers:
  - name: web-identity
    image: millegalb/identity.test:0.0.1

    ports:
      - containerPort: 80
