apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport-identity
spec:
  type: NodePort #ClusterIP oder NodePort oder LoadBalancer
  ports:
  - port: 8011 # Port Innerhalb des Cluster
    targetPort: 80 # Port der App welche im Pod läuft
    nodePort: 31112 # Port vom Node (aller Nodes) im Cluster
    protocol: TCP
  selector:
    app: web-id
