apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort #ClusterIP oder NodePort oder LoadBalancer
  ports:
  - port: 80 # Port Innerhalb des Cluster
    targetPort: 8080 # Port der App welche im Pod läuft
    nodePort: 31111 # Port vom Node (aller Nodes) im Cluster
    protocol: TCP
  selector:
    app: web
